select * from medicos
select * from pacientes
select * from consultas

CREATE TABLE MEDICOS(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAr(100) NOT NULL,
	TELEFONE VARCHAR(100) NOT NULL,
	CRM VARCHAR(20) NOT NULL UNIQUE,
	ESPECIALIDADE VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE
);
CREATE TABLE PACIENTES(
	id SERIAL PRIMARY KEY,
    	nome VARCHAR(100) NOT NULL,
    	email VARCHAR(100) NOT NULL UNIQUE,
    	telefone VARCHAR(20) NOT NULL,
    	cpf VARCHAR(14) NOT NULL UNIQUE,
    	logradouro VARCHAR(100) NOT NULL,
    	numero VARCHAR(10),
    	complemento VARCHAR(50),
    	bairro VARCHAR(50) NOT NULL,
    	cidade VARCHAR(50) NOT NULL,
    	uf CHAR(2) NOT NULL,
    	cep VARCHAR(9) NOT NULL,
    	ativo BOOLEAN DEFAULT TRUE
);
CREATE Table CONSULTAS(
	id SERIAL PRIMARY KEY,
    	pacientes_id INT NOT NULL,
    	medicos_id INT,
    	data_hora TIMESTAMP NOT NULL,
    	ativa BOOLEAN DEFAULT TRUE,
    	CONSTRAINT fk_pacientes FOREIGN KEY (pacientes_id) REFERENCES pacientes(id),
    	CONSTRAINT fk_medicos FOREIGN KEY (medicos_id) REFERENCES medicos(id)
);
